micronaut:
  server:
    port: 8080
#consul:
#  client:
#    registration:
#      enabled: true
#    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
#netty:
#  default:
#    allocator:
#      max-order: 3
